In [29]:
import numpy as np

In [30]:
a = [1,2,3,4]
b = [5,6,7,8]
[a[i] + b[i] for i in range(len(a))]

[6, 8, 10, 12]

In [31]:
a = np.array ([1,2,3,4])
b = np.array([4,5,6,7])
a+b

array([ 5,  7,  9, 11])

In [37]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
np.eye(3,3).astype("int32").dtype

dtype('int32')

In [39]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a

array([1, 2, 3, 4])

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a

array([1, 2, 3, 4])

In [49]:
a[a>2]

array([3, 4])

In [52]:
a

array([1, 2, 3, 4])

In [57]:

np.linspace(0,4,2)

array([0., 4.])

In [60]:
a =np.array([1,2,3])
a**2

array([1, 4, 9])

In [61]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [62]:
a+b

array([[ 6,  8],
       [10, 12]])

In [63]:
a*b

array([[ 5, 12],
       [21, 32]])

In [64]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [65]:
a = [1,2,3,4,5,6,7,8,9]

In [66]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [67]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [69]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [71]:
import numpy as np
np.linalg.det(a)

-9.51619735392994e-16

In [72]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [73]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [74]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [78]:
a = np.array([1,2,3,4,5,6,7,8,9,10,4,1])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  1])

In [79]:
np.reshape(np.reshape(a,(3,4)),(6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 4,  1]])

In [80]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  1])

In [83]:
 np.resize(a,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  4,  1]])

In [84]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  1])

In [85]:
a = np.array([1,2,3,4,5,6,7,8,9,10,4,1])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  1])

In [86]:
b =np.reshape(a,(3,4))

In [87]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  4,  1]])

In [88]:
a is b

False

In [90]:
np.resize(a,(4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  4,  1]])

In [91]:
np.split(a,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10,  4,  1])]

In [8]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
b= arr